### ISSUE TITLE
Update ufs-bundle to build and run atmosphere-only configurations

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/ufs-bundle#12]
## Description

The current code in the develop branch is not functional. We need to update the ufs-bundle `CMakeLists.txt` and `README.md` to build and run atmosphere-only configurations of JEDI+UFS, and document it.

This will require several updates to other repositories, which will be covered in a separate issue (since this is a lengthy process).

**Comment by symoore90** [comment]
Hi @climbfuji , is there anyway to break this issue down into smaller story points?

**Comment by climbfuji** [comment]
> Hi @climbfuji , is there anyway to break this issue down into smaller story points?

In theory, yes. However, this is 99% done. The PR is ready for review and already approved by one person. Needs one more approval to merge, and then I can cash in the 21 points. It seems like breaking it up "retrospectively" doesn't make a lot of sense?

**Comment by symoore90** [comment]
@climbfuji , correct if you are already done with this issue then breaking it into smaller pieces after the fact is not needed. Thanks for the update.

**Comment by climbfuji** [comment]
We merged this PR!
