### ISSUE TITLE
Add the capability to run from UFS coldstart initial conditions

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/ufs-bundle#14]
## Description

PR https://github.com/JCSDA/ufs-bundle/pull/9 adds the capability to do UFS ATM only warmstart runs. To do coldstart runs, the I/O layer in fv3-jedi needs to be modified and the test yamls updated.

**Comment by shlyaeva** [comment]
I can assist with this if needed, let me know (I don't know which files need to be read for cold start, so wouldn't be able to just work on it by myself)

**Comment by danholdaway** [comment]
There's a test that transforms cold starts into warm starts so I would have thought the ability to read cold starts already exists. But maybe there is a detail I'm overlooking. It actually runs two tests. This one https://github.com/JCSDA-internal/fv3-jedi/blob/develop/test/testinput/convertstate_gfs_coldstartwinds.yaml and then this one https://github.com/JCSDA-internal/fv3-jedi/blob/develop/test/testinput/convertstate_gfs_vertremap.yaml

**Comment by climbfuji** [comment]
Do you think we can make this work for the UFS (atm standalone, ng-godas, fully-coupled)?

**Comment by danholdaway** [comment]
I don't know about the coupled system very well and specifically what the non-atmospheric components do in regards to cold starts.

**Comment by climbfuji** [comment]
In my naive thinking, the easiest way to turn cold start ICs into useable restart ICs is to run the model standalone (i.e. the `ufs_model` executable, not through JEDI) for one time step with the flag to write 0h restart files on (in `model_configure`) and then simply kick JEDI off from there. This way you are starting with a model state in JEDI that is truly consistent with what the model is doing. For example, all the adiabatic init, rebalancing etc that happens for coldstart runs.

**Comment by danholdaway** [comment]
That's probably a better way to do it to be honest. That way you don't have to keep any code in sync between JEDI and UFS. We did this so we could have an entirely JEDI-based workflow for training the static background error covariance model. We had to convert some 2500 ensemble members from Gaussian grid to cube sphere stream function and velocity potential. So we ran change res to get them to cube then these fv3-jedi variable transforms to make them warm and then the transform to stream function and velocity potential. If I recall correctly it was going to take a long time to run the C768 model for one timestep 2500 times and be complicated to setup the workflows.

**Comment by climbfuji** [comment]
@cmgas I think your currently open PRs will close this issue, right?

**Comment by cmgas** [comment]
Yes!

**Comment by cmgas** [comment]
Standalone only, though

**Comment by climbfuji** [comment]
If you agree, then please make your PR resolve this issue :-)
