### ISSUE TITLE
Add CI tests for ufs-bundle repo

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/ufs-bundle#17]
## Description

Need to CI test ufs-bundle. We should do this on the bundle repo level to avoid replication of what the bundle's `CMakeLists.txt` does in the fv3-jedi repo.

**Comment by climbfuji** [comment]
@eap @shlyaeva @ytremolet ufs-bundle is currently out of scope of the new CI pipeline. But with the move to using JEDI develop, we should really get the CI tests up and running. I am not interested in constantly fixing problems introduced by updates to JEDI code post-commit.

I suggest we use the same infrastructure and setup as we use for spack-stack and skylab CI at the moment: github self-hosted runner on the dedicated AWS Parallelcluster for CI.

Any objections?

**Comment by ytremolet** [comment]
At some point in the future (when is another question) UFS will be part of jedi-bundle, that should solve the problem. In the meantime so there is no reason to do the CI differently, is it the same setup we use for jedi-bundle?

**Comment by shlyaeva** [comment]
I think CI on this would be very useful (run nightly or with some other regularity?). I don't have any input on how to set it up

**Comment by climbfuji** [comment]
> At some point in the future (when is another question) UFS will be part of jedi-bundle, that should solve the problem. In the meantime so there is no reason to do the CI differently, is it the same setup we use for jedi-bundle?

I don't think we are in the position to include another bundle, since the full CI pipeline of jedi-bundle isn't in place yet. (EDIT: I also think that ufs-bundle is more complicated, since it not only contains ecbuild bundles but also an external cmake project). I was thinking of doing the same nightly runs that we do for skylab (on the same machine). (EDIT: That is easy and quick to implement, uses existing capabilities (no new development, no new processes, not doing anything different than what we are already doing for skylab) and will give us an idea if something broke the bundle on the same day at least).
