### ISSUE TITLE
Get ufs-jedi-bundle into working state

### ISSUE THREAD

**Issue by mark-a-potts** [JCSDA/ufs-bundle#2]
The initial commit of the ufs-jedi-bundle included work to link in SOCA and MOM6 via the UFS, but is not operational. 

The fv3-jedi feature/ufs branch should be merged to develop and then used to build and test the JEDI-UFS (ATM-only) connections.

**Comment by climbfuji** [comment]
This issue needs to be broken up into smaller pieces. I am closing it in favor of #12 and similar issues.
