### ISSUE TITLE
ufs-bundle CI broken

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/ufs-bundle#35]
**ufs-bundle is broken, at least in CI (not tested locally yet)**

CI ran fine during the night of Wednesday/Thursday (Aug 23/24), but failed Thursday/Friday and Friday/Saturday. The build (linker) error doesn’t make much sense to me, because it fails in linking the ufs-weather-model libraries together, and as far as I know updates where made to the JEDI components only (see the discourse yesterday). Nonetheless, it’s broken. See for example:

https://github.com/JCSDA/ufs-bundle/actions/runs/5982688486/job/16237115235

**Comment by cmgas** [comment]
Should be repaired now

**Comment by climbfuji** [comment]
Wow, thanks! I kicked off a CI run https://github.com/JCSDA/ufs-bundle/actions/runs/6004173541/job/16284169489 to verify.

**Comment by climbfuji** [comment]
It's still failing, but the thing is that the linker error is within the ufs-weather-model code, which itself should not have been affected by the change in fv3jedi .

**Comment by cmgas** [comment]
There was definitely another error that I fixed, too. Let me look into the other changes that appeared

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/ufs-bundle/pull/36
