### ISSUE TITLE
Update ufs-bundle to use head of develop of ufs-weather-model

### ISSUE THREAD

**Issue by mark-a-potts** [JCSDA/ufs-bundle#44]
Update the ufs-bundle to use an un-modified version of the ufs-weather-model for coupling. 

Additionally, ensure that namelists and other configuration files are kept in sync with the ufs-wm by creating a dynamic run directory for warmstart cases used by ctest when UFS is built in ATM-only configuration.

**Comment by climbfuji** [comment]
Let's make sure we coordinate on this work - we've got an idea on how to get there ... a few steps needed. But thanks for creating the issue.

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/ufs-bundle/pull/43
