### ISSUE TITLE
botocore issues on orion

### ISSUE THREAD

**Issue by kbhargava** [JCSDA/ufs-bundle#53]
I get the following error when I try to submit an experiment on orion
`ImportError: cannot import name 'DEPRECATED_SERVICE_NAMES' from 'botocore.docs' (/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/envs/unified-env/install/intel/2022.0.2/py-botocore-1.29.84-ots42in/lib/python3.10/site-packages/botocore/docs/__init__.py)`

I am following the instructions mentioned in the README in this repo. I am able to bypass this issue if I add `module load ewok-env` to my setup.

I am using spack-stack 1.5.1 and intel compiler.

**Comment by climbfuji** [comment]
@kbhargava Is this still an issue?

**Comment by kbhargava** [comment]
Let me test and get back to you.

**Comment by kbhargava** [comment]
Yes, still get it. I have this in my config script.
```
module purge
module use /work/noaa/epic/role-epic/spack-stack/orion/modulefiles
module load python/3.9.2
module load ecflow/5.8.4
module load mysql/8.0.31

module use /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/envs/unified-env/install/modulef+ iles/Core
module load stack-intel/2022.0.2
module load stack-intel-oneapi-mpi/2021.5.1
module load stack-python/3.10.8

#module load ewok-env
module load jedi-ufs-env
module load fms/2023.02.01
module load awscli/1.27.84

source $JEDI_ROOT/setup.sh 
```

I have to uncomment `module load ewok-env` to  be able to submit an experiment.

**Comment by climbfuji** [comment]
Thanks Kriti. Ok, we'll need to look at this again when spack-stack-1.7.0 is ready.

**Comment by climbfuji** [comment]
sorry I didn't get to this before my vacation. Will try again in April!

**Comment by climbfuji** [comment]
@kbhargava We just merged https://github.com/JCSDA-internal/r2d2/pull/591, there's hope that this will resolve your issue on Orion with botocore.

**Comment by climbfuji** [comment]
@kbhargava I just tried this again with spack-stack-1.7.0 and Intel on Orion. Using jedi-bundle develop and the skylab workflow repos develop. I believe the most-recent r2d2 update fixed the issue. I was able to run
```
create_experiment.py --test jedi-bundle/skylab/experiments/qg-fullDA.yaml 2>&1 | tee create_experiment_qg-fullDA.log
```
without errors. Can you check please?

**Comment by kbhargava** [comment]
> @kbhargava I just tried this again with spack-stack-1.7.0 and Intel on Orion. Using jedi-bundle develop and the skylab workflow repos develop. I believe the most-recent r2d2 update fixed the issue. I was able to run
> 
> ```
> create_experiment.py --test jedi-bundle/skylab/experiments/qg-fullDA.yaml 2>&1 | tee create_experiment_qg-fullDA.log
> ```
> 
> without errors. Can you check please?

Let me test and update you once I have it running

**Comment by kbhargava** [comment]
works fine for me.

**Comment by climbfuji** [comment]
Oh great, thanks for testing! I'll close this issue.
