### ISSUE TITLE
Rename this repository to ufs-bundle

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/ufs-bundle#6]
To be consistent with the existing bundle names, can we use "ufs-bundle" instead of "ufs-jedi-bundle"?

We have: fv3-bundle, mpas-bundle, um-bundle, lfric-bundle, ...

**Comment by aerorahul** [comment]
works for me.

**Comment by aerorahul** [comment]
Please include @CoryMartin-NOAA @guillaumevernieres as they are direct beneficiaries of this bundle.

**Comment by climbfuji** [comment]
I also added @danholdaway - there is a repository "ufs-bundle" in JCSDA-internal that is very old (last update three years ago) that I think should be superseded but this repository (currently called "ufs-jedi-bundle").

Note that even if we rename this bundle and delete the old "ufs-bundle" in JCSDA-internal, this bundle will stay in JCSDA public - definitely not move behind closed curtains.

**Comment by CoryMartin-NOAA** [comment]
`ufs-bundle` is fine with me. IMO I think the bundle repos are not really that important as they will likely live inside comprehensive workflows anyways.

**Comment by mark-a-potts** [comment]
That is fine with me. I don't think I have permissions to make that change in the jcsda public repo, however.

**Comment by climbfuji** [comment]
> That is fine with me. I don't think I have permissions to make that change in the jcsda public repo, however.

Ok, thanks! I'll make the change and also rename the existing ufs-bundle in the internal repo to "ufs-bundle-old"

**Comment by climbfuji** [comment]
This was done in github. The remaining step, i.e. the renaming of `ufs-jedi-bundle` to `ufs-bundle` in the top-level `README.md` is included in the forthcoming PR for getting ufs-bundle into a working state. I will close this issue as completed.
