### ISSUE TITLE
ufs-bundle CI runs failing since 08/17/2024

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/ufs-bundle#73]
https://github.com/JCSDA/ufs-bundle/actions/runs/10446950847/job/28925129558

**Comment by climbfuji** [comment]
@mark-a-potts @fmahebert FYI

**Comment by mark-a-potts** [comment]
It looks like the S3 bucket data is still refreshing. It may take the rest of the day to finish.

**Comment by mark-a-potts** [comment]
I was able to run the tests successfully on Hera today. The build/fv3-jedi/test/Data/ModelRunDirs/UFS_warmstart*/* files might need to be removed before re-running.

**Comment by climbfuji** [comment]
Last night's CI tests went through - closing as "fixed itself"
